export default {
  DATA_VALIDATING: 'DATA_VALIDATING',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR',
  DATA_POST_SUCCESS:'DATA_POST_SUCCESS',
  DATA_POST_ERROR:'DATA_POST_ERROR',
  DATA_POSTING:'DATA_POSTING',
};
